name: å¤‡ä»½äºŒè¿›åˆ¶ç¨‹åº

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 */3 * *'

jobs:
  build:
    name: ä»»åŠ¡
    runs-on: ubuntu-latest
    steps:
    - name: åˆ›å»ºæˆ–æ›´æ–°å‘è¡Œç‰ˆ
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: "v1.0.0"
        body: |
          ## æ—¥å¿—
          - ğŸ”¥ ä¸–ç•Œæ½®æµæµ©æµ©è¡è¡ï¼Œé¡ºä¹‹åˆ™æ˜Œï¼Œé€†ä¹‹åˆ™äº¡ã€‚
        draft: false
        prerelease: false
        overwrite: true

    - name: ä¸Šä¼ äºŒè¿›åˆ¶ç¨‹åº
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # åˆ›å»ºç›®å½•
        mkdir dist && cd dist
        
        # ä¸‹è½½äºŒè¿›åˆ¶
        curl -s -o nezha-agent_linux_amd64.zip https://github.com/nezhahq/agent/releases/latest/download/nezha-agent_linux_amd64.zip
        
        ls -a
        
        for FILE in ./dist/*; do
          echo "Uploading $FILE..."
          curl -sSL \
            -XPOST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: $(file -b --mime-type $FILE)" \
            --data-binary @"$FILE" \
            "${{ steps.create_release.outputs.upload_url }}?name=$(basename $FILE)"
        done
